### PR TITLE
Emb retract screw

### PR DESCRIPTION
**Pull request by Reason1337**
This branch implements the functionality to retract the brakes

### CODE REVIEW

**Comment by mkristien** [comment]
Fix the merge conflict with develop first.

**Comment by mkristien** [comment]
Can you fix indentation to follow our style guide? One level of indentation should be 2 spaces, and namespaces do not introduce new indentations levels.

Also, this modules seems to be quite important. Where is it documented? How to figure out how it interacts with the rest of the code without a detailed study of the code?

**Comment by Reason1337** [comment]
The functions are commented in their header files, should I add more comments within the code or how do you think I should improve the readability of the code?

**Comment by mkristien** [comment]
Perhaps, in the `main.h` you could explain in detail how the whole embrake module is constructed, what does Main, EmbrakeManager, and the actual Embrakes do, how they interact with the rest of the code.

**Pull request merged**
